#overrides .bashrc
export PATH="${HOME}/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/bin:$PATH"
export EDITOR='vim'

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi